version: "3.9"

services:
  backend:
    build:
      context: ./PoultryFarmBack 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./PoultryFarmFront 
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

